### ISSUE TITLE
div navigation 

### ISSUE THREAD

**Issue by matuzo** [matuzo/HTMHell#45]
Context: Main navigation on a personal website.

```
<div class="nav">
  <div>
    <div>about</div>
    <div>thoughts</div>
  </div>
</div>
```

**Comment by christophfreyer** [comment]
<nav>
  <ul class="nav">
    <li>about</li>
    <li>thoughts</li>
  </ul>
</nav>

**Comment by matuzo** [comment]
Cool, thanks. A few things I believe we need to work on to complete it.

- [ ] Why `nav`. What are the advantages?
- [ ] Why a list?
- [ ] Why `ul`? Is `ol` fine as well?
- [ ] What's wrong with divs?
- [ ] What's wrong with using JS to link to pages? 
- [ ] Links are missing.

You don't have to work on everything. We can do it together. :)

**Comment by christophfreyer** [comment]
good code:
```
<nav>
  <ul class="nav">
    <li><a href="#">about</a></li>
    <li><a href="#">thoughts</a></li>
  </ul>
</nav>
```
# Why nav. What are the advantages?

Always use a <nav> for the mainnavigation. The advantage of this element is, that it represents a section with navigation links to other pages or even also on the same page. The as <nav> marked up section will will tell screenreaders where to find the navigation and shows the structure of a page because <nav> is oppsite to a div a named element. Assistive technologies will be able to skip this section on demand.
         
# Why a list?

Best use for navigations are lists. They show that there are a couple of elements which belong structural together. A screenreader will call them as a list and also count the number of items. For blind people this would be an additional aid. Even without CSS you will get a meaningful display.

# Why ul? Is ol fine as well?

Unordered lists <ul> and Ordered lists <ol> will work the same way, but use the <ul> if the meaning of the order is not important. In most cases of navigation menus it is used this way. Only if the order of the list-items really matters, then you should use for semanticly correctness the ordered list <ol>.

# What's wrong with divs?

A div is an anonymous blockelement and has got only the meaning of division. But it does not say what kind of division it is. To use it as a container for the navigation it would need an aria-attribute in addition (here: role="navigation").  At W3C it is mentioned to "view the div element as an element of last resort, for when no other element is suitable. Use of the div element instead of more appropriate elements leads to poor accessibility for readers and poor maintainability for authors."

# What's wrong with using JS to link to pages?

Don't use only JS to link to a page. In case users have JS disabled, it would not be possible to use this link. The benefit of dealing with a correct link-structure, HTML will automatically show your users in an unmisinterpretable way (colour, underline, etc.) that this element is a link and also its status.

materials: 
https://www.w3.org/TR/html52/sections.html#the-nav-element
https://www.w3.org/WAI/tutorials/menus/structure/
also: https://inclusive-components.design/menus-menu-buttons/ (the book version)

hope it's all real english and not german witth english words. Feel free for corrections and additions. Have you any ideas for corrections, etc.?

**Comment by matuzo** [comment]
Awesome! I tried to turn this into a post (I try to keep it short). Please tell me if you want me to change/add anything.

Here's a preview: <https://dev--htmhell.netlify.com/18-main-divigation/>

**Comment by christophfreyer** [comment]
Great! It's all in it and so easy-reading. - Thank You!
